require 'rubygems'

$:<< './lib'
require 'digital_ocean'


client = DigitalOcean::Client.new('4WhguuLiYGzYPLhBq0HZz','3z8rnRYv3xcOoBH3IyXQDJQ36Ni61mosZ6wPL81vB')

client.droplets

client.droplets

client.droplets[21357].refresh

# retreives from memory
client.droplets[21357] 

#retrieves from memory with refresh
client.droplets.get(21357, true)

client.droplets[21357].refresh

client.droplets[21357].power_off

existing_droplets =  client.droplets.find_by_name("AutoGenerated")


existing_droplets.each do |droplet|
  droplet.destroy
end
  
# new_droplet = client.droplets.create({
   # :name => "AutoGenerated",
   # :image_id => 2675,
   # :size_id => 32,
   # :region_id => 1,
# })
# puts "new droplet #{new_droplet}"

#puts "regions"
#puts client.regions
#puts "sizes"
#puts client.sizes
puts "images"

client.images.each do |key, image|
  puts "#{image.id} #{image.name}, #{image.distribution}"
end


